//
//  SetRowViews.swift (Redesigned)
//  WRKT
//
//  Simplified set row components with clear active state
//

import SwiftUI

private typealias Theme = ExerciseSessionTheme

// MARK: - Rest Zone

private enum RestZone: Equatable {
    case strength   // reps <= 5, science recommends 4 min
    case pump       // reps > 12, science recommends 1 min

    var label: String { self == .strength ? "Strength sets" : "High-rep sets" }
    var tip: String { self == .strength ? "4 min rest for strength sets" : "1 min rest for high-rep sets" }
    var dismissKey: String { self == .strength ? "rest_rec_strength_dismiss_count" : "rest_rec_pump_dismiss_count" }
}

// MARK: - Set Row Unified (Redesigned - Simple & Clear)

struct SetRowUnified: View {
    let index: Int
    @Binding var set: SetInput
    let unit: WeightUnit
    let exercise: Exercise
    let isActive: Bool
    let isGhost: Bool
    let hasActiveTimer: Bool  // Whether this set has an active rest timer
    let onDuplicate: () -> Void
    let onActivate: () -> Void
    let onLogSet: () -> Void  // New: explicit log action

    @EnvironmentObject private var store: WorkoutStoreV2

    // Don't observe timer to avoid re-renders every second - access directly when needed
    private var timerManager: RestTimerManager { RestTimerManager.shared }

    @AppStorage("weight_step_kg") private var weightStepKg: Double = 2.5

    private let defaultWorkingReps = 10
    private var step: Double {
        if unit == .kg { return weightStepKg }
        // Map kg increment to nearest standard lb increment
        switch weightStepKg {
        case 0.5: return 1.25
        case 1.0: return 2.5
        default: return 5.0  // 2.5 kg
        }
    }
    private var displayWeight: Double { unit == .kg ? set.weight : (set.weight * 2.20462) }

    @State private var isEditingReps = false
    @State private var isEditingWeight = false
    @FocusState private var focusedField: Field?

    @State private var showRestBanner = false
    @State private var restBannerZone: RestZone? = nil
    @State private var restDebounceWorkItem: DispatchWorkItem? = nil
    @AppStorage("rest_rec_strength_dismiss_count") private var strengthDismissCount: Int = 0
    @AppStorage("rest_rec_pump_dismiss_count") private var pumpDismissCount: Int = 0

    enum Field {
        case reps
        case weight
    }

    var body: some View {
        VStack(spacing: 0) {
            if set.isCompleted {
                completedRow
            } else if isActive {
                expandedRow
            } else {
                pendingRow
            }
        }
        .background(ChamferedRectangle(.large).fill(backgroundColor))
        .overlay(ChamferedRectangle(.large).stroke(borderColor, lineWidth: isActive ? 2 : 1))
        .opacity(rowOpacity)
        .animation(.easeInOut(duration: 0.2), value: isActive)
        .animation(.easeInOut(duration: 0.2), value: set.isCompleted)
        .animation(.easeInOut(duration: 0.2), value: hasActiveTimer)
        .onTapGesture {
            if focusedField != nil {
                focusedField = nil
                isEditingReps = false
                isEditingWeight = false
            } else if !set.isCompleted && !isActive {
                set.isAutoGeneratedPlaceholder = false
                onActivate()
            }
        }
        .onChange(of: focusedField) { _, newValue in
            if newValue != .reps { isEditingReps = false }
            if newValue != .weight { isEditingWeight = false }
        }
        .onAppear {
            seedFromMemoryIfNeeded()
            if set.tag == .working { applyWeightSuggestion() }
        }
        .onChange(of: set.reps) { _, newReps in
            scheduleRestBannerEvaluation(reps: newReps)
        }
        .onChange(of: isActive) { _, active in
            if !active {
                restDebounceWorkItem?.cancel()
                withAnimation(.easeInOut(duration: 0.2)) { showRestBanner = false }
            }
        }
    }

    // MARK: - Completed row (collapsed)

    private var completedRow: some View {
        HStack(spacing: 10) {
            Image(systemName: "checkmark.circle.fill")
                .dsFont(.body, weight: .semibold)
                .foregroundStyle(Theme.accent)

            Text("Set \(index)")
                .dsFont(.subheadline, weight: .semibold)
                .foregroundStyle(Theme.secondary)

            if hasActiveTimer {
                RestTimerBadgeIsolated()
            }

            Spacer()

            Text(completedSummary)
                .dsFont(.subheadline, weight: .semibold, monospacedDigits: true)
                .foregroundStyle(Theme.text)

            if let rpe = set.rpe {
                Text("RPE \(formatRPE(rpe))")
                    .dsFont(.caption, weight: .semibold)
                    .padding(.vertical, 4)
                    .padding(.horizontal, 8)
                    .foregroundStyle(Theme.accent)
                    .background(Theme.accent.opacity(0.12), in: Capsule())
                    .overlay(Capsule().stroke(Theme.accent.opacity(0.3), lineWidth: 1))
            }
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 10)
    }

    // MARK: - Pending row (not completed, not active)

    private var pendingRow: some View {
        HStack(spacing: 10) {
            Circle()
                .strokeBorder(Theme.secondary.opacity(0.3), lineWidth: 1.5)
                .frame(width: 8, height: 8)

            Text("Set \(index)")
                .dsFont(.subheadline, weight: .semibold)
                .foregroundStyle(Theme.secondary)

            Spacer()

            Text(completedSummary)
                .dsFont(.subheadline, weight: .semibold, monospacedDigits: true)
                .foregroundStyle(Theme.secondary)
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 10)
    }

    // MARK: - Expanded row (active only)

    private var expandedRow: some View {
        VStack(spacing: 0) {
            // Header
            HStack(spacing: 12) {
                HStack(spacing: 6) {
                    if isActive {
                        Circle()
                            .fill(Theme.accent)
                            .frame(width: 8, height: 8)
                    } else {
                        Circle()
                            .strokeBorder(Theme.secondary.opacity(0.3), lineWidth: 1.5)
                            .frame(width: 8, height: 8)
                    }
                    Text("Set \(index)")
                        .dsFont(.subheadline, weight: isActive ? .bold : .semibold)
                        .foregroundStyle(Theme.text)
                }

                Spacer()

                TagDotCycler(tag: $set.tag)
                    .disabled(isGhost)
            }
            .padding(.horizontal, 16)
            .padding(.top, 8)
            .padding(.bottom, 6)

            Divider()
                .background(Theme.border)
                .padding(.horizontal, 16)

            // Reps + Weight steppers
            HStack(spacing: 16) {
                VStack(spacing: 2) {
                    Text("REPS")
                        .dsFont(.caption2, weight: .semibold)
                        .foregroundStyle(Theme.secondary)

                    HStack(spacing: 8) {
                        StepperButton(
                            systemName: "minus.circle.fill",
                            isEnabled: !isGhost && set.reps > 1,
                            color: Theme.accent.opacity(0.8)
                        ) {
                            if set.reps > 1 {
                                set.reps -= 1
                                set.autoWeight = false
                                set.isAutoGeneratedPlaceholder = false
                                UIImpactFeedbackGenerator(style: .light).impactOccurred()
                            }
                        }

                        if isEditingReps {
                            TextField("", value: Binding(
                                get: { set.reps },
                                set: { newReps in
                                    set.reps = newReps
                                    set.autoWeight = false
                                    set.isAutoGeneratedPlaceholder = false
                                }
                            ), format: .number)
                                .keyboardType(.numberPad)
                                .focused($focusedField, equals: .reps)
                                .dsFont(.title2, weight: .bold, monospacedDigits: true)
                                .foregroundStyle(Theme.text)
                                .multilineTextAlignment(.center)
                                .frame(minWidth: 40)
                        } else {
                            Text("\(set.reps)")
                                .dsFont(.title2, weight: .bold, monospacedDigits: true)
                                .foregroundStyle(Theme.text)
                                .frame(minWidth: 40)
                                .contentShape(Rectangle())
                                .onTapGesture {
                                    if !isGhost {
                                        isEditingReps = true
                                        focusedField = .reps
                                    }
                                }
                        }

                        StepperButton(
                            systemName: "plus.circle.fill",
                            isEnabled: !isGhost,
                            color: Theme.accent
                        ) {
                            set.reps += 1
                            set.autoWeight = false
                            set.isAutoGeneratedPlaceholder = false
                            UIImpactFeedbackGenerator(style: .light).impactOccurred()
                        }
                    }
                }
                .frame(maxWidth: .infinity)

                Rectangle()
                    .fill(Theme.border)
                    .frame(width: 1, height: 50)

                VStack(spacing: 2) {
                    Text("WEIGHT (\(unit.rawValue))")
                        .dsFont(.caption2, weight: .semibold)
                        .foregroundStyle(Theme.secondary)

                    HStack(spacing: 8) {
                        StepperButton(
                            systemName: "minus.circle.fill",
                            isEnabled: !isGhost && displayWeight > 0,
                            color: Theme.accent.opacity(0.8)
                        ) {
                            let newWeight = max(0, displayWeight - step)
                            set.weight = (unit == .kg) ? newWeight : newWeight / 2.20462
                            set.autoWeight = false
                            set.isAutoGeneratedPlaceholder = false
                            UIImpactFeedbackGenerator(style: .light).impactOccurred()
                        }

                        if isEditingWeight {
                            TextField("", value: Binding(
                                get: { displayWeight },
                                set: { newDisplay in
                                    let kg = (unit == .kg) ? newDisplay : newDisplay / 2.20462
                                    set.weight = max(0, kg)
                                    set.autoWeight = false
                                    set.isAutoGeneratedPlaceholder = false
                                }
                            ), format: .number.precision(.fractionLength(0...1)))
                                .keyboardType(.decimalPad)
                                .focused($focusedField, equals: .weight)
                                .dsFont(.title2, weight: .bold, monospacedDigits: true)
                                .foregroundStyle(Theme.text)
                                .multilineTextAlignment(.center)
                                .frame(minWidth: 70, maxWidth: 100)
                        } else {
                            Text(String(format: "%.1f", displayWeight))
                                .dsFont(.title2, weight: .bold, monospacedDigits: true)
                                .foregroundStyle(Theme.text)
                                .frame(minWidth: 70, maxWidth: 100)
                                .contentShape(Rectangle())
                                .onTapGesture {
                                    if !isGhost {
                                        isEditingWeight = true
                                        focusedField = .weight
                                    }
                                }
                        }

                        StepperButton(
                            systemName: "plus.circle.fill",
                            isEnabled: !isGhost,
                            color: Theme.accent
                        ) {
                            let newWeight = displayWeight + step
                            set.weight = (unit == .kg) ? newWeight : newWeight / 2.20462
                            set.autoWeight = false
                            set.isAutoGeneratedPlaceholder = false
                            UIImpactFeedbackGenerator(style: .light).impactOccurred()
                        }
                    }
                }
                .frame(maxWidth: .infinity)
            }
            .padding(.horizontal, 16)
            .padding(.vertical, 8)

            // Rest recommendation banner
            if showRestBanner, let zone = restBannerZone, isActive {
                restRecommendationBanner(zone: zone)
                    .transition(.opacity.combined(with: .move(edge: .top)))
            }

            // Log button — only on active sets
            if isActive && !isGhost {
                Divider()
                    .background(Theme.border)
                    .padding(.horizontal, 16)

                Button(action: onLogSet) {
                    HStack(spacing: 8) {
                        Image(systemName: "checkmark.circle.fill")
                        Text("Log This Set")
                            .fontWeight(.semibold)
                    }
                    .dsFont(.subheadline)
                    .foregroundStyle(Color.black)
                    .frame(maxWidth: .infinity)
                    .frame(height: 44)
                    .background(Theme.accent)
                    .clipShape(ChamferedRectangle(.medium))
                }
                .buttonStyle(.plain)
                .padding(.horizontal, 16)
                .padding(.vertical, 8)
            }
        }
    }

    // MARK: - RPE chip strip

    private var rpeChipStrip: some View {
        HStack(spacing: 6) {
            ForEach([6.0, 7.0, 8.0, 8.5, 9.0, 9.5, 10.0], id: \.self) { value in
                let selected = set.rpe == value
                Button {
                    set.rpe = selected ? nil : value
                    UIImpactFeedbackGenerator(style: .light).impactOccurred()
                } label: {
                    Text(formatRPE(value))
                        .dsFont(.caption, weight: .semibold)
                        .padding(.vertical, 4)
                        .padding(.horizontal, 6)
                        .foregroundStyle(selected ? Color.black : Theme.accent)
                        .background(selected ? Theme.accent : Theme.accent.opacity(0.1),
                                    in: Capsule())
                        .overlay(Capsule().stroke(Theme.accent.opacity(selected ? 0 : 0.3),
                                                 lineWidth: 1))
                }
                .buttonStyle(.plain)
                .animation(.easeInOut(duration: 0.12), value: selected)
            }

            Spacer()
        }
        .padding(.horizontal, 12)
        .padding(.top, 4)
        .padding(.bottom, 8)
    }

    // MARK: - Rest Recommendation Banner

    private func scheduleRestBannerEvaluation(reps: Int) {
        restDebounceWorkItem?.cancel()
        let work = DispatchWorkItem { [reps] in
            evaluateRestZone(reps: reps)
        }
        restDebounceWorkItem = work
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5, execute: work)
    }

    private func evaluateRestZone(reps: Int) {
        guard set.tag == .working, !isGhost, isActive else {
            withAnimation(.easeInOut(duration: 0.2)) { showRestBanner = false }
            return
        }
        let current = Int(RestTimerPreferences.shared.restDuration(for: exercise))
        let zone: RestZone?
        if reps <= 5, abs(current - 240) > 30 {
            zone = .strength
        } else if reps > 12, abs(current - 60) > 30 {
            zone = .pump
        } else {
            zone = nil
        }
        let dismissCount = zone == .strength ? strengthDismissCount : (zone == .pump ? pumpDismissCount : 0)
        withAnimation(.easeInOut(duration: 0.2)) {
            restBannerZone = zone
            showRestBanner = zone != nil && dismissCount < 3
        }
    }

    @ViewBuilder
    private func restRecommendationBanner(zone: RestZone) -> some View {
        HStack(spacing: 10) {
            Image(systemName: "clock")
                .dsFont(.caption)
                .foregroundStyle(Theme.secondary)

            Text(zone.tip)
                .dsFont(.caption)
                .foregroundStyle(Theme.secondary)

            Spacer()

            Button {
                let wasStrength = zone == .strength
                withAnimation(.easeInOut(duration: 0.2)) { showRestBanner = false }
                if wasStrength { strengthDismissCount += 1 } else { pumpDismissCount += 1 }
            } label: {
                Image(systemName: "xmark")
                    .dsFont(.caption2)
                    .foregroundStyle(Theme.secondary)
                    .padding(6)
                    .contentShape(Rectangle())
            }
            .buttonStyle(.plain)
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 6)
    }

    // MARK: - Helpers

    private var completedSummary: String {
        let w = String(format: displayWeight.truncatingRemainder(dividingBy: 1) == 0 ? "%.0f" : "%.1f",
                       displayWeight)
        return "\(set.reps) × \(w)\(unit.rawValue)"
    }

    private func formatRPE(_ value: Double) -> String {
        value.truncatingRemainder(dividingBy: 1) == 0
            ? String(format: "%.0f", value)
            : String(format: "%.1f", value)
    }

    private var backgroundColor: Color {
        if set.isCompleted && hasActiveTimer {
            // Completed with active timer - slightly highlighted to show it's "resting"
            return Theme.accent.opacity(0.08)
        } else if set.isCompleted {
            // Completed without timer - muted
            return Theme.accent.opacity(0.04)
        } else if isActive {
            // Active set
            return Theme.surface2
        } else {
            // Inactive set
            return Theme.surface
        }
    }

    private var borderColor: Color {
        if set.isCompleted && hasActiveTimer {
            // Completed with active timer - more prominent border
            return Theme.accent.opacity(0.5)
        } else if set.isCompleted {
            // Completed without timer - subtle border
            return Theme.accent.opacity(0.2)
        } else if isActive {
            // Active set - full accent border
            return Theme.accent
        } else {
            // Inactive set
            return Theme.border
        }
    }

    private var rowOpacity: Double {
        if set.isCompleted && hasActiveTimer {
            // Completed with timer - more visible to emphasize resting
            return 0.85
        } else if set.isCompleted {
            // Completed without timer - more muted
            return 0.65
        } else {
            // Active or inactive - full opacity
            return 1.0
        }
    }

    private func seedFromMemoryIfNeeded() {
        guard set.tag == .working, set.autoWeight, !set.didSeedFromMemory else { return }
        let looksEmpty = (set.reps == 0 && set.weight == 0)
        guard looksEmpty else { return }
        if let last = store.lastWorkingSet(exercise: exercise) {
            set.reps = last.reps
            set.weight = last.weightKg
            set.didSeedFromMemory = true
            return
        }
        set.reps = (set.reps > 0) ? set.reps : defaultWorkingReps
        set.didSeedFromMemory = true
    }

    private func applyWeightSuggestion() {
        guard set.autoWeight else { return }
        if set.reps <= 0 { set.reps = defaultWorkingReps }
        if let w = store.suggestedWorkingWeight(for: exercise, targetReps: set.reps) {
            let snapped: Double
            if unit == .kg {
                snapped = (w / step).rounded() * step
            } else {
                let lb = w * 2.20462
                snapped = ((lb / step).rounded() * step) / 2.20462
            }
            set.weight = max(0, snapped)
        }
    }

}

// MARK: - Tag Dot Cycler (Simplified)

struct TagDotCycler: View {
    @Binding var tag: SetTag

    var body: some View {
        Button {
            cycle()
        } label: {
            HStack(spacing: 6) {
                Circle()
                    .fill(tag.color)
                    .frame(width: 8, height: 8)
                Text(tag.label)
                    .dsFont(.caption, weight: .semibold)
                    .foregroundStyle(Theme.text)
            }
            .padding(.horizontal, 10)
            .padding(.vertical, 6)
            .background(tag.color.opacity(0.15))
            .clipShape(Capsule())
            .overlay(Capsule().stroke(tag.color.opacity(0.3), lineWidth: 1))
        }
        .buttonStyle(.plain)
       
        .accessibilityLabel("Set type \(tag.label)")
    }

    private func cycle() {
        let all = SetTag.allCases
        if let idx = all.firstIndex(of: tag) {
            let next = all.index(after: idx)
            // Safely cycle through tags, fallback to .working if array is empty (should never happen)
            tag = next < all.endIndex ? all[next] : (all.first ?? .working)
        } else {
            tag = .working
        }
        UIImpactFeedbackGenerator(style: .light).impactOccurred()
    }
}

// MARK: - Stepper Button (Optimized for One-Handed Use)

private struct StepperButton: View {
    let systemName: String
    let isEnabled: Bool
    let color: Color
    let action: () -> Void

    @GestureState private var isPressingDown = false
    @State private var longPressTimer: Timer?

    var body: some View {
        Image(systemName: systemName)
            .dsFont(.title2)
            .foregroundStyle(isEnabled ? color : Theme.secondary.opacity(0.3))
            .frame(width: 44, height: 44)
            .contentShape(Rectangle())
            .gesture(
                DragGesture(minimumDistance: 0)
                    .updating($isPressingDown) { _, state, _ in
                        state = true
                    }
                    .onChanged { _ in
                        if isEnabled && longPressTimer == nil {
                            // First action on press
                            action()
                            UIImpactFeedbackGenerator(style: .light).impactOccurred()

                            // Start timer after brief delay for long press
                            DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
                                if isPressingDown && isEnabled {
                                    startLongPress()
                                }
                            }
                        }
                    }
            )
            .onChange(of: isPressingDown) { _, pressing in
                if !pressing {
                    stopLongPress()
                }
            }
            .onDisappear { stopLongPress() }
    }

    private func startLongPress() {
        guard longPressTimer == nil else { return }
        UIImpactFeedbackGenerator(style: .medium).impactOccurred()

        // Repeat action every 0.1 seconds while holding
        longPressTimer = Timer.scheduledTimer(withTimeInterval: 0.1, repeats: true) { _ in
            if isEnabled {
                action()
            } else {
                stopLongPress()
            }
        }
    }

    private func stopLongPress() {
        longPressTimer?.invalidate()
        longPressTimer = nil
    }
}

// MARK: - Isolated Timer Badge
/// Isolates timer observation to prevent SetRowViews re-renders
private struct RestTimerBadgeIsolated: View {
    @ObservedObject private var timerManager = RestTimerManager.shared

    var body: some View {
        if timerManager.isRunning {
            Button {
                timerManager.stopTimer()
                UIImpactFeedbackGenerator(style: .medium).impactOccurred()
            } label: {
                HStack(spacing: 4) {
                    Image(systemName: "timer")
                        .dsFont(.caption, weight: .medium)
                    Text(formatTime(timerManager.remainingSeconds))
                        .dsFont(.caption, weight: .semibold, monospacedDigits: true)
                        .lineLimit(1)
                        .minimumScaleFactor(0.8)
                    Text("•")
                        .dsFont(.caption2)
                    Text("Cancel")
                        .dsFont(.caption, weight: .semibold)
                        .lineLimit(1)
                    Image(systemName: "xmark.circle.fill")
                        .dsFont(.caption)
                }
                .foregroundStyle(ExerciseSessionTheme.accent)
                .padding(.horizontal, 10)
                .padding(.vertical, 5)
                .background(ExerciseSessionTheme.accent.opacity(0.15))
                .clipShape(ChamferedRectangle(.small))
                .overlay(ChamferedRectangle(.small).stroke(ExerciseSessionTheme.accent.opacity(0.3), lineWidth: 1))
                .lineLimit(1)
                .fixedSize(horizontal: false, vertical: true)
            }
            .buttonStyle(.plain)
        }
    }

    private func formatTime(_ seconds: TimeInterval) -> String {
        let mins = Int(seconds) / 60
        let secs = Int(seconds) % 60
        return String(format: "%d:%02d", mins, secs)
    }
}
